// Generated by gencpp from file tocabi_msgs/torqueCommand.msg
// DO NOT EDIT!


#ifndef TOCABI_MSGS_MESSAGE_TORQUECOMMAND_H
#define TOCABI_MSGS_MESSAGE_TORQUECOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tocabi_msgs
{
template <class ContainerAllocator>
struct torqueCommand_
{
  typedef torqueCommand_<ContainerAllocator> Type;

  torqueCommand_()
    : mode(0)
    , position()
    , traj_time(0.0)  {
      position.assign(0.0);
  }
  torqueCommand_(const ContainerAllocator& _alloc)
    : mode(0)
    , position()
    , traj_time(0.0)  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef int32_t _mode_type;
  _mode_type mode;

   typedef boost::array<double, 33>  _position_type;
  _position_type position;

   typedef double _traj_time_type;
  _traj_time_type traj_time;





  typedef boost::shared_ptr< ::tocabi_msgs::torqueCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tocabi_msgs::torqueCommand_<ContainerAllocator> const> ConstPtr;

}; // struct torqueCommand_

typedef ::tocabi_msgs::torqueCommand_<std::allocator<void> > torqueCommand;

typedef boost::shared_ptr< ::tocabi_msgs::torqueCommand > torqueCommandPtr;
typedef boost::shared_ptr< ::tocabi_msgs::torqueCommand const> torqueCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tocabi_msgs::torqueCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tocabi_msgs::torqueCommand_<ContainerAllocator1> & lhs, const ::tocabi_msgs::torqueCommand_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.position == rhs.position &&
    lhs.traj_time == rhs.traj_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tocabi_msgs::torqueCommand_<ContainerAllocator1> & lhs, const ::tocabi_msgs::torqueCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tocabi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tocabi_msgs::torqueCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tocabi_msgs::torqueCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tocabi_msgs::torqueCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4be12da3fbfaceede31bd84358b05cd";
  }

  static const char* value(const ::tocabi_msgs::torqueCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4be12da3fbfaceeULL;
  static const uint64_t static_value2 = 0xde31bd84358b05cdULL;
};

template<class ContainerAllocator>
struct DataType< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tocabi_msgs/torqueCommand";
  }

  static const char* value(const ::tocabi_msgs::torqueCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n"
"float64[33] position\n"
"float64 traj_time\n"
;
  }

  static const char* value(const ::tocabi_msgs::torqueCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.position);
      stream.next(m.traj_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct torqueCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tocabi_msgs::torqueCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tocabi_msgs::torqueCommand_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "traj_time: ";
    Printer<double>::stream(s, indent + "  ", v.traj_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOCABI_MSGS_MESSAGE_TORQUECOMMAND_H
