(cl:in-package tocabi_msgs-msg)
(cl:export '(RATIO-VAL
          RATIO
          HEIGHT-VAL
          HEIGHT
          PELV_PITCH-VAL
          PELV_PITCH
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          SOLVER-VAL
          SOLVER
          CONTACTREDIS-VAL
          CONTACTREDIS
          MAINTAIN_LC-VAL
          MAINTAIN_LC
          LEFT-VAL
          LEFT
          RIGHT-VAL
          RIGHT
          LEFT_FOOT-VAL
          LEFT_FOOT
          RIGHT_FOOT-VAL
          RIGHT_FOOT
          LEFT_HAND-VAL
          LEFT_HAND
          RIGHT_HAND-VAL
          RIGHT_HAND
          TIME-VAL
          TIME
          MODE-VAL
          MODE
          L_X-VAL
          L_X
          L_Y-VAL
          L_Y
          L_Z-VAL
          L_Z
          L_ROLL-VAL
          L_ROLL
          L_PITCH-VAL
          L_PITCH
          L_YAW-VAL
          L_YAW
          R_X-VAL
          R_X
          R_Y-VAL
          R_Y
          R_Z-VAL
          R_Z
          R_ROLL-VAL
          R_ROLL
          R_PITCH-VAL
          R_PITCH
          R_YAW-VAL
          R_YAW
          WALKING_ENABLE-VAL
          WALKING_ENABLE
          PATTERN-VAL
          PATTERN
          PATTERN2-VAL
          PATTERN2
          COMCONTROL-VAL
          COMCONTROL
          IK_MODE-VAL
          IK_MODE
          DOB-VAL
          DOB
          IMU-VAL
          IMU
          MOM-VAL
          MOM
          MPC-VAL
          MPC
          FIRST_FOOT_STEP-VAL
          FIRST_FOOT_STEP
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          WALKING_HEIGHT-VAL
          WALKING_HEIGHT
          THETA-VAL
          THETA
          STEP_LENGTH_X-VAL
          STEP_LENGTH_X
          STEP_LENGTH_Y-VAL
          STEP_LENGTH_Y
          CUSTOMTASKGAIN-VAL
          CUSTOMTASKGAIN
          ACC_P-VAL
          ACC_P
          POS_P-VAL
          POS_P
          POS_D-VAL
          POS_D
          ANG_P-VAL
          ANG_P
          ANG_D-VAL
          ANG_D
))